### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by hbui3** [jaromeyer/mipurifier-esphome#1]
Hi Jaro,

sorry for the stupid question, but how can I flash this to my Purifier Pro (didnt check if there is an ESP32 yet, but if it has one). What device do I need? ( I found your project because my Purifier always makes trouble with the Homeassistant Xiaomi Integration)

Best regards

**Comment by jaromeyer** [comment]
Hi hbui3,

The only thing you really need is a USB-to-UART converter which you have to connect to TX (GPIO1) and RX (GPIO3) and of course ground. On my device I also had to connect GPIO0 and GPIO2 to ground for the ESP32 to enter download mode. Then you can flash it like any other ESP using the ESPHome commandline tools.
Feel free to ask for clarification if something is still unclear.

-Jaro

**Comment by jaromeyer** [comment]
I also advise you to first dump the original firmware using esptool before attempting to install ESPHome. This way you can just restore it if something goes wrong.
