### ISSUE TITLE
Mi Air Purifier 3H AC-M6-SC manufactured in 2020 - working!

### ISSUE THREAD

**Issue by neutrinus** [jaromeyer/mipurifier-esphome#10]
SKU: FJY4031GL
Board rev: AC-M6-B01 Rev 3-XR

This is a confirmation that it worked flawlessly. Thank you!

![PXL_20231107_180933558](https://github.com/jaromeyer/mipurifier-esphome/assets/1677760/698b1706-e799-414e-a06c-38e638a71ac3)

**Comment by maaaax** [comment]
Works too on 2x AC-M6-SC here. Great project! :D
