### ISSUE TITLE
support for Xiaomi Mi Air Purifier Pro H​ 

### ISSUE THREAD

**Issue by neutrinus** [jaromeyer/mipurifier-esphome#11]
I have Xiaomi Mi Air Purifier Pro H​  at my home and strong incentive to flash it esphome :)

I haven't seen any disassembly pictures of this model, anybody know if there is a ESP32 inside? 

Do you have any procedure to dump protocol between ESP32 and the other chip?

**Comment by jaromeyer** [comment]
You can inspect the communication between the MCUs by attaching a logic analyzer to pins 27 & 28 of the ESP32 module. If you don't own one, cheap 8ch models that work with sigrok or Saleae Logic are available on Aliexpress. Another possibility would be using two separate UART-USB converters and connecting each RX to one of the data lines. A simple python script can be used to then partly parse the protocol.

**Comment by neutrinus** [comment]
So first things first, I've got it open. My exact model: Mi Air Purifier Pro H, AC-M13-SC, manufactured in 2020.

 Good news, there is ESP-WROOM-32D inside!
 
 
![PXL_20231111_112623755](https://github.com/jaromeyer/mipurifier-esphome/assets/1677760/fbaa75a0-5a29-4a6f-a30b-05982258304b)

Next step: connect rigol ds1054z with sigrok and hope to capture some traffic. 

@jaromeyer  should I run a specific set of commands, or just few of them to understand if the protocol is the same?

As I have the case open, do I need to put filter inside to dump the communication?  I'm aware that the power supply has exposed 230V, will be carefull.

**Comment by neutrinus** [comment]
There is a place for 5 header pins (P14) on this board:

- G - ground
- R - ESP_PIN27 connection to STM chip
- T - ESP_PIN28 connection to STM chip
- LR - ESP_PIN34 (U0_TXD)
- LT - ESP_PIN35  (U0_RXD)


LT and LT will be nice for future flashing. Near the GPIO0 (pin 25) there is a connected place for a pogopin.

Still not sure where would be convenient to insert 3.3V but this is for future.


So, I was sniffing a bit with my oscilloscope, here are the results.

![DS1Z_QuickPrint2](https://github.com/jaromeyer/mipurifier-esphome/assets/1677760/d2957fe0-387b-4d0b-b921-86ce58d03560)
![DS1Z_QuickPrint1](https://github.com/jaromeyer/mipurifier-esphome/assets/1677760/400381a7-9f37-40b6-94da-3baa85ffc90d)


My next step will be to have it sniffing on my laptop, screenshots are far from proper way of doing it.

**Comment by neutrinus** [comment]
@jaromeyer  the protocol dump is here: https://drive.google.com/drive/folders/1cJbJcp92DgPfoT_0Iic1dnSMXsqybPhR?usp=drive_link

(dumped with pulseview)

Can you please verify if this is the same protocol? Thank you!

**Comment by jaromeyer** [comment]
nice work! the general protocol seems to be the same - human readable ASCII commands over UART. the STM32 periodically sends `get_down` which is acknowledged with either some command or `down_none` if there is nothing to do. everything else can be answered with `ok`. as a next step you should check if the command ids match with the ones documented [here](../blob/main/protocol.pdf) and if there are new commands that the older model didn't support. also make sure that the STM32 isn't sending some special query on start up, expecting a specific response to continue. i had a quick look at the startup sequence and didn't notice anything weird.

**Comment by neutrinus** [comment]
I'm hunting for changes in protocol, this is what I have found so far:

Enable notification sound: (beep?)
`down set_properties 5 2 50`

Disable notification sound: (beep?)
`down set_properties 5 2 0`



Startup sequence: 
```
model zhimi.airpurifier.vb2
ok

ble_config set 2645 1002
ok

mcu_version 1002
ok
```


I saw also:
```
properties_changed 2 4 0
ok

properties_changed 2 2 false
ok

properties_changed 15 7 2
ok
```
(they are not documented in protocol.pdf, no idea what they do)

Other commands seem to be the same.

So, my next step would be probably backup original firmware via esptool and try to flash it with esphome. I don't have spare ESP32 module.

**Comment by neutrinus** [comment]
To flash:
- connect GPIO0 and GPIO2 to GND
- and connect the pins to G, LR, LT  to your USB-serial adapter
- connect P1 connector (as the usb adapter cannot supply enough current)


verify connection:
```
marek@blacky:~/Pobrane/esptool-linux-amd64$ ./esptool flash_id
esptool.py v4.7.0
Found 1 serial ports
Serial port /dev/ttyUSB0
Connecting...
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting...
Detecting chip type... ESP32
Chip is unknown ESP32 (revision v1.0)
Features: WiFi, BT, Single Core, 240MHz, VRef calibration in efuse, Coding Scheme 3/4
Crystal is 40MHz
MAC: XXXX
Stub is already running. No upload is necessary.
Manufacturer: 68
Device: 4016
Detected flash size: 4MB
Hard resetting via RTS pin...
marek@blacky:~/Pobrane/esptool-linux-amd64$

```

backup original flash content:
```
./esptool read_flash 0x00000 0x400000 backup.img
```

It's working. Yeeee!

Thank you @jaromeyer  for this great project. You can add the Pro H to the supported devices :)

**Comment by neutrinus** [comment]
![image](https://github.com/jaromeyer/mipurifier-esphome/assets/1677760/6394e8f7-9b5a-4954-9758-123972598547)


Just a side note, this purifier is way better build, no plastic latches - everything has nice screws. The disassembly is really nice.

**Comment by mshrem** [comment]
> To flash:
> 
> * connect GPIO0 and GPIO2 to GND
> * and connect the pins to G, LR, LT  (P14) to your USB-serial adapter
> * connect P1 connector (as the usb adapter cannot supply enough current)
> 
> verify connection:
> 
> ```
> marek@blacky:~/Pobrane/esptool-linux-amd64$ ./esptool flash_id
> esptool.py v4.7.0
> Found 1 serial ports
> Serial port /dev/ttyUSB0
> Connecting...
> Detecting chip type... Unsupported detection protocol, switching and trying again...
> Connecting...
> Detecting chip type... ESP32
> Chip is unknown ESP32 (revision v1.0)
> Features: WiFi, BT, Single Core, 240MHz, VRef calibration in efuse, Coding Scheme 3/4
> Crystal is 40MHz
> MAC: XXXX
> Stub is already running. No upload is necessary.
> Manufacturer: 68
> Device: 4016
> Detected flash size: 4MB
> Hard resetting via RTS pin...
> marek@blacky:~/Pobrane/esptool-linux-amd64$
> ```
> 
> backup original flash content:
> 
> ```
> ./esptool read_flash 0x00000 0x400000 backup.img
> ```
> 
> Then follow the instructions.
> 
> And it's working. Yeeee!
> 
> Thank you @jaromeyer for this great project. You can add the Pro H to the supported devices :)

Hi there i plan on doing this mod over the weekend since i got 2 units for very cheap , so i can place the 5 pins on the P14 connector but on the home assistant forum someone used the connections on the [p12](https://community.home-assistant.io/t/link-xiaomi-air-purifier-3-3h-with-custom-esphome-firmware/656741/23)  conector , i am no expert when doing this things but i can follow along . 

Do you have any images on how the connections should be made ?

**Comment by neutrinus** [comment]
@mshrem  I just have the extra photo, maybe it will guide you.

![PXL_20231216_192525134](https://github.com/jaromeyer/mipurifier-esphome/assets/1677760/0288f52c-622c-4271-ad2c-dca45ca12512)

**Comment by mshrem** [comment]
@neutrinus 

Yes that helps a lot , so from your picture you are using the solder point next to the IO0 (pin 25) to GND (pin 38) , that pulls low IO0 , then M3.3V to provide power right ? 

Next the connections are made with the P14 TX ,RX  and GND.

But from reading the tutorial it seems that you also need to pull low also the IO2 (pin24) did you  neeeded to do something for this ? 

From the other post in the home assistant forum he seems to be getting 3.3 and GND from the P12 so might be a good idea to try that and see if it workds in that case no need for soldering.
