### ISSUE TITLE
Why is this project not shown in google?

### ISSUE THREAD

**Issue by maaaax** [jaromeyer/mipurifier-esphome#12]
Every time I try to find this project, I have to go to the comments in
https://www.flamingo-tech.nl/2021/05/03/xiaomi-air-purifier-3h-reverse-engineering-part-3-esp32-dump/
For example, a search for "Air Purifier 3H esphome github" doesn't list it. Maybe not everyone gets the same results, of course..
Yes, bookmarking.. But it should show up.

**Comment by jaromeyer** [comment]
That's indeed very weird, but I think it has improved a bit (at least for me). Searching for "mi Air Purifier esphome" no shows this repo and the corresponding thread on the home assistant forum as the first two results.
