### ISSUE TITLE
Home Assistant Thread and More Resources

### ISSUE THREAD

**Issue by OkhammahkO** [jaromeyer/mipurifier-esphome#13]
Hey there is a Home Assistant thread on your ESPHome device over here now.
https://community.home-assistant.io/t/link-xiaomi-air-purifier-3-3h-with-custom-esphome-firmware/656741/9

Some people like myself are adding more flashing and disassembly tips.

Might be worth linking to the thread in your read-me. Or feel free to lift photo's / video links from it.

Thanks for your work on this!!!

**Comment by jaromeyer** [comment]
I just added a link. Thanks for the heads-up and your valuable contributions to the thread!
