### ISSUE TITLE
Mi purifier 4 Lite issue

### ISSUE THREAD

**Issue by moto25** [jaromeyer/mipurifier-esphome#3]
Hi there, first its amazing work you did and thank you very much for that. I was able to flash AC-M17-SC and i see entities in home assistant but all sensors are unknown and controls when triggered dont do anything. When i press via power button device works couple seconds, it shows on the OLD dispaly, then i hear long beep, then short beep, and mi goes off, display off and ESP restarts. This makes me thing the device isnt working properly with your code. I am able to upload new code without issues now. Any idea how to proceed to make my device  work? Thank you

**Comment by jaromeyer** [comment]
Do you have a backup of the stock firmware? Even if not I would start by connecting a logic analzer to the serial bus between the ESP and the other MCU. See if it is sending completelly different messages or maybe it is just using a different baud rate.

**Comment by moto25** [comment]
I dont have backup stock fw but i have one more same device here. BTW there is home assistant plugin for local HA control of mi devices with stock firmware, maybe this can help us further to see what commands are used on each different device?
https://github.com/al-one/hass-xiaomi-miot 
this is my device:
https://home.miot-spec.com/s/zhimi.airp.rmb1
Spec:
https://home.miot-spec.com/spec/zhimi.airp.rmb1

I connected ttl reader to the stock fw and below are some logs:

[mi_home_app_on.txt](https://github.com/jaromeyer/mipurifier-esphome/files/10986533/mi_home_app_on.txt)
[mi_home_app_off.txt](https://github.com/jaromeyer/mipurifier-esphome/files/10986531/mi_home_app_off.txt)
[miot_auto_app_off.txt](https://github.com/jaromeyer/mipurifier-esphome/files/10986535/miot_auto_app_off.txt)
[miot_auto_app_on.txt](https://github.com/jaromeyer/mipurifier-esphome/files/10986536/miot_auto_app_on.txt)
[press_button_off.txt](https://github.com/jaromeyer/mipurifier-esphome/files/10986537/press_button_off.txt)
[press_button_on.txt](https://github.com/jaromeyer/mipurifier-esphome/files/10986538/press_button_on.txt)

As i said earlier there is no sensor data or possibility to control my device via your code. Any idea how to move on would be helpful. Thank you

**Comment by jaromeyer** [comment]
@moto25 sorry for the late response, I was busy working on other things. The network protocol that you mentioned unfortunately is completely different from the one used between the MCUs. However from your logs it looks like the AC-M17-SC is using the same protocol as my Purifier 3H. Do you have a logic analyzer or second serial adapter so you could monitor both directions of the serial connection between ESP32 and STM32?

**Comment by jaromeyer** [comment]
stale

**Comment by dhewg** [comment]
@moto25 did you get this any further by chance?

@jaromeyer Dunno if you realised, but your protocol.pdf matches the miot protocol specs for your 3/3h: https://home.miot-spec.com/spec?type=urn%3Amiot-spec-v2%3Adevice%3Aair-purifier%3A0000A007%3Azhimi-mb3%3A2
So the 4 lite needs at least some SIIDs/PIIDs adjusted. E.g. for the on/off switch it's 2,1 instead of 2,2.

**Comment by moto25** [comment]
@dhewg Hey, no didnt move on i gave it up. You have idea where to modify the code to make it working? Thanx

**Comment by dhewg** [comment]
So far I just adapted the code for the 4lite ids: 
[4lite.patch.txt](https://github.com/jaromeyer/mipurifier-esphome/files/13928005/4lite.patch.txt)
With that it can receive from the STM, yet transmit to it isn't working, at least we never get any response to any command.
Any ideas?

**Comment by moto25** [comment]
maybe tx_pin isnt  GPIO17?

**Comment by dhewg** [comment]
That wasn't it. Just a missing \r and flush() :)
This works for me: [0001-wip-4lite.patch.txt](https://github.com/jaromeyer/mipurifier-esphome/files/13928988/0001-wip-4lite.patch.txt)
There's still room for improvement, but it's good enough for one day

**Comment by moto25** [comment]
Amazing, it works! Thank you for the update

**Comment by dhewg** [comment]
Nice 👌I've added the Motor RPM sensor by now, and with that is exposes all feature I've been using with the vendor fw.

This can't be merged though, as the IDs are hardcoded for each device. I'll check how that can be solved, unsure yet as I just started with esphome.

**Comment by moto25** [comment]
Thats great! Keep us updated please

**Comment by KristijanL** [comment]
maybe a stupid question, do i need to connect GPIO 16 and 17 in Mi purifier 4 Lite anywhere?

**Comment by dhewg** [comment]
I've played a bit with esphome components and so far it's working nicely for me.
See https://github.com/dhewg/esphome-miot/blob/main/config/zhimi.airp.rmb1.yaml
You don't even have to clone the repo, just fetch that file and build it locally.

Did you have an updated vendor firmware on your device? What's the reported mcu version with that ^ build?

**Comment by dhewg** [comment]
@KristijanL no, those are lanes to the mcu on the board.
You just need the rx, tx and gnd for serial, those are in a row and even labeled on the board. You can short the two pins above there to keep the device in bootloader mode. No soldering required ;)

From there I just flashed it with `esphome upload --device /dev/ttyUSB0 config/zhimi.airp.rmb1.yaml`

**Comment by KristijanL** [comment]
works! thank you @dhewg

**Comment by dhewg** [comment]
Nice! When did you last update the firmware? What mcu version is reported with esphome?

**Comment by KristijanL** [comment]
Device info:
esp32doit-devkit-v1
by Espressif
Firmware: 2023.12.7 (Jan 17 2024, 18:08:36)
is this the information you are looking for? ( i am not so fluent in esphome )

**Comment by dhewg** [comment]
It's only printed on the serial output for now, in green color. I get `[I][miot:235]: MCU Version: 0040`

**Comment by KristijanL** [comment]
[19:58:49][C][miot:101]:   MCU Version: 0058

**Comment by dhewg** [comment]
Ok, I guess mine is rather outdated then... thanks!

**Comment by jaromeyer** [comment]
@dhewg nice work, esphome-miot repo looks promising. ! i wasn't aware of the miot-spec website.

**Comment by dhewg** [comment]
Thanks!

It should work with your 3H too, you basically just have to adapt the SIID/PIIDs, and add/remove differences. But that's just a manner of syncing it with the miot spec. Wanna give that a try?

Do you know how to reset the STM from the ESP? I assume there's a STM reset pin wired to some ESP gpio?
