### ISSUE TITLE
Xiaomi Air Purifier 4 Compact

### ISSUE THREAD

**Issue by jds11111** [jaromeyer/mipurifier-esphome#5]
I just took this one apart, and it looks promising. The board varies from your picture only slightly, and uses an ESP-WROOM-32D.
Before I do anything else, maybe I should try to extract the stock firmware on the chip?  I have only flashed such chips before, so, if you are interested in it, would it be something like this: https://cyberblogspot.com/how-to-save-and-restore-esp8266-and-esp32-firmware/? 
![2023-07-27-143434](https://github.com/jaromeyer/mipurifier-esphome/assets/15203860/aa0ddf70-7552-4b80-8f04-ecdf0fd88e2a)

**Comment by jds11111** [comment]
So, I finally got around to downloading the original firmware on the device using epstool.py.  Attached is the firmware
[esp32_firmware.tar.gz](https://github.com/jaromeyer/mipurifier-esphome/files/12262399/esp32_firmware.tar.gz)

**Comment by jds11111** [comment]
I have already flashed it, but there are problems. I was using a fork of this code, but the ESP32 board just keeps crashing.

**Comment by jaromeyer** [comment]
Can you share a log?

**Comment by jds11111** [comment]
Sure:

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

**Comment by jaromeyer** [comment]
sorry for never answering, i was busy doing other work :/ were you able to find a solution?

**Comment by jaromeyer** [comment]
stale

**Comment by jds11111** [comment]
Sorry, got tied up in other things. It looked to me like the chip might have been locked down, so I desoldered it to put in another one. Unfortunately, the binary doesn't flash successfully to a new chip. I have an ESP32-WROOM-32D in one of [these things](https://www.amazon.com/gp/product/B08K2JKNRK/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1), so it is easy flash. Is there a binary to test?

**Comment by tujdfhxyvweyka5** [comment]
@jds11111 did you manage to flash your firmware back ? I also have this model, I'd be happy to have your feedback and give your help if needed

**Comment by jds11111** [comment]
Naw, I sort of quit. I realized that there was not too much need to connect it. Maybe later this summer, when I have free time.
